### ISSUE TITLE
时间间隔有问题

### ISSUE THREAD

**Issue by wjzyxbaby** [Mai-Onsyn/VeloVoice#1]
同语速下，同类软件生成的音频比这个的短，我把音频丢尽软件查看，同一行的文字时间一样的。但在换行时发现本软件的时间间隔比其他软件长。而且不同语速下，这个间隔是一样，而其他同类软件，会根据语速加快，间隔也相对缩短。

**Comment by Mai-Onsyn** [comment]
这是因为软件会优先按照换行符 然后按照设置的文本切片符号 将一个很长的文本拆分成若干个小的片段转换 然后合并 这样来防止因为文本量过大而导致转换卡住 因为是一条一条发送的所以中间断句断行会有一个固定的时间间隔 且比一次性发送的要长点 这个软件是为小说设计的 因此我觉得这个问题没必要细抠
