### ISSUE TITLE
根据最新的设置好了后，一直抓不到，自己改了个python的也能用

### ISSUE THREAD

**Issue by DavidLiu0536** [Mai-Onsyn/VeloVoice#10]
不知道哪里有问题，我就自己找网上攻略，改了个python的，也能用。

**Comment by DavidLiu0536** [comment]
运行的时候，后面提示还没结束

**Comment by DavidLiu0536** [comment]
部署完api后，获取api的里面的内容的时候，发现是空的。

**Comment by DavidLiu0536** [comment]
用虚拟机安装了后，还是访问的时候，是空值

**Comment by DavidLiu0536** [comment]
我自己用python改了个版本，用chatgpt捣鼓一下午都不行，最后换claude，1个小时搞定。测试后，放到里面，也能生成，晚点我发上来。

自己生成个
一、proxy_script.py文件、
`from mitmproxy import ctx, http
import urllib.parse
import requests
from datetime import datetime
import logging
import os
import json

# 配置日志
log_dir = os.path.dirname(os.path.abspath(__file__))
log_file = os.path.join(log_dir, 'websocket_capture.log')

logging.basicConfig(
    level=logging.DEBUG,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(log_file, mode='w'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

# 创建一个不使用代理的session
session = requests.Session()
session.trust_env = False

class WebSocketInterceptor:
    def __init__(self):
        self.logger = logger

    def _send_to_api(self, data):
        try:
            response = session.post(
                "http://127.0.0.1:8000/store_sec",
                json=data,
                timeout=5,
                proxies={}
            )
            if response.status_code == 200:
                self.logger.info(f"Successfully sent data to API")
        except Exception as e:
            self.logger.error(f"Error sending to API: {e}")

    def request(self, flow: http.HTTPFlow) -> None:
        if "speech.platform.bing.com" in flow.request.pretty_url:
            try:
                parsed_url = urllib.parse.urlparse(flow.request.pretty_url)
                query_params = urllib.parse.parse_qs(parsed_url.query)
                
                # 提取参数并使用新的键名
                sec_gec = query_params.get("Sec-MS-GEC", [""])[0]
                sec_gec_version = query_params.get("Sec-MS-GEC-Version", [""])[0]
                
                if sec_gec and sec_gec_version:
                    data = {
                        "Sec-MS-GEC": sec_gec,
                        "Sec-MS-GEC-Version": sec_gec_version,
                        "timestamp": datetime.now().isoformat()
                    }
                    self.logger.info(f"Found parameters: {data}")
                    self._send_to_api(data)
            except Exception as e:
                self.logger.error(f"Error: {e}")

addons = [WebSocketInterceptor()]`
二、api_server.py
`from fastapi import FastAPI
from pydantic import BaseModel, Field
import uvicorn
from datetime import datetime

app = FastAPI()

# 存储最新的数据
latest_data = {}

class SecData(BaseModel):
    # 使用 Field 来重命名字段
    Sec_MS_GEC: str = Field(alias="Sec-MS-GEC")
    Sec_MS_GEC_Version: str = Field(alias="Sec-MS-GEC-Version")
    timestamp: str

    class Config:
        # 允许使用别名
        allow_population_by_field_name = True
        # 设置JSON序列化时使用别名
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }

@app.post("/store_sec")
async def store_sec(data: SecData):
    global latest_data
    latest_data = {
        "Sec-MS-GEC": data.Sec_MS_GEC,
        "Sec-MS-GEC-Version": data.Sec_MS_GEC_Version,
        "timestamp": data.timestamp
    }
    return {"status": "success"}

@app.get("/get_sec")
async def get_sec():
    return latest_data

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
`
三、一个html页面
这个用文件夹里带着的那个就行，写个python不定时重启这个就行
怎么使用？
先用python api_server.py,再启动mitmdump -s proxy_script.py -p 22516
然后访问
http://127.0.0.1:8000/get_sec
如果你想外面能访问可以把api里面的那个127.0.0.1改成0.0.0.0
因为我用的是虚拟机，所以改了。

**Comment by pitayala** [comment]
大佬麻烦问下这个现在还能用吗，html页面在哪里啊

**Comment by DavidLiu0536** [comment]
可以用，html页面在开源作者提供的那个程序里面。

**Comment by Mai-Onsyn** [comment]
我本来就是拿learnin9/edgetts-GecAPI改的 因为我不会python 这个是真的不会用 就用java写了 而且是临时写的 问题很多 看样子就我能部属

**Comment by Mai-Onsyn** [comment]
使用test-v0.6.2 已经不需要api了
