### ISSUE TITLE
语音分段问题

### ISSUE THREAD

**Issue by xyjsb** [Mai-Onsyn/VeloVoice#2]
我希望有一个可以将整体音频长度切成一段一段的功能，例如全长有120min，设置50min后会分成50min*2+20min的音频并且添加序号

**Comment by Mai-Onsyn** [comment]
Test-v0.3不是就有这个功能了吗
当然 为确保一句话的完整性 分段的音频的时长不会是准确的50min 不过偏差大多在2s内
