### ISSUE TITLE
生成的音频比特率是48kbps，有没有能提高音质的方法呀

### ISSUE THREAD

**Issue by cxfShannon** [Mai-Onsyn/VeloVoice#5]

**Comment by Mai-Onsyn** [comment]
抱歉我还没搞透EdgeTTS的音频格式 所以是不能改 当然如果非要改 可以在源码中的mai_onsyn.VeloVoice.NetWork.TTS.EdgeTTSClient.java中的静态变量mp3Format改成你想要的 然后自己编译
