### ISSUE TITLE
好像又没法用了

### ISSUE THREAD

**Issue by pitayala** [Mai-Onsyn/VeloVoice#7]

**Comment by DavidLiu0536** [comment]
是的，又挂了

**Comment by DavidLiu0536** [comment]
这个要改哪里呢？
> 可以自己替换下这个方法,本地生成下,这个生成方法提出来有段时间了,没发现什么问题,目前是可以的 public static void UpdateSec_MS_GEC() { long currentTime = System.currentTimeMillis(); if (currentTime - lastUpdateTimestamp < COOLDOWN_PERIOD_MS) { return; } lastUpdateTimestamp = currentTime; try { String SEC_MS_GEC_Version = "1-130.0.2849.68"; long ticks = (long) (Math.floor((System.currentTimeMillis()/1000.0)+11644473600l)*10000000); long roundedTicks =ticks-(ticks % 3000000000L); String str = roundedTicks+"6A5AA1D4EAFF4E9FB37E23D68491D6F4"; MessageDigest sha256 = MessageDigest.getInstance("SHA-256"); byte[] hash = sha256.digest(String.valueOf(roundedTicks).concat("6A5AA1D4EAFF4E9FB37E23D68491D6F4").getBytes(StandardCharsets.UTF_8)); StringBuilder hexString = new StringBuilder(); for (byte b : hash) { String hex = Integer.toHexString(0xff & b); if (hex.length() == 1) { hexString.append('0'); } hexString.append(hex); } String SEC_MS_GEC = hexString.toString().toUpperCase(); URL = String.format( "wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&Sec-MS-GEC=%s&Sec-MS-GEC-Version=%s", SEC_MS_GEC, SEC_MS_GEC_Version); System.out.println("Adjusted SEC_MS_GEC to : " + SEC_MS_GEC); System.out.println("Adjusted SEC_MS_GEC_Version to : " + SEC_MS_GEC_Version); } catch (NoSuchAlgorithmException e) { throw new RuntimeException(e); } }

**Comment by PoliceZ** [comment]
mai_onsyn.VeloVoice.App.Constants#UpdateSec_MS_GEC  这个方法,你既然选择使用开源的东西,还是要看下别人的代码实现,这样才能更好的使用

**Comment by PoliceZ** [comment]
我的是在没加代理的版本修改的,那你可以回退下代码,完整的类,我这里放出来
package mai_onsyn.VeloVoice.App;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class Constants {

    public static String URL;

    public static final String USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55";
    public static final String ORIGIN = "chrome-extension://jdiccldimpdaibmpdkjnbmckianbfold";
    public static final String VOICES_LIST_URL = "https://speech.platform.bing.com/consumer/speech/synthesize/readaloud/voices/list?trustedclienttoken=6A5AA1D4EAFF4E9FB37E23D68491D6F4";

    static {
        UpdateSec_MS_GEC();
    }


    private static final long COOLDOWN_PERIOD_MS = 30 * 1000;
    private static volatile long lastUpdateTimestamp = 0;


    public static void UpdateSec_MS_GEC() {
        long currentTime = System.currentTimeMillis();
        if (currentTime - lastUpdateTimestamp < COOLDOWN_PERIOD_MS) {
            return;
        }
        lastUpdateTimestamp = currentTime;
        try {
            String SEC_MS_GEC_Version = "1-130.0.2849.68";
            long ticks = (long) (Math.floor((System.currentTimeMillis()/1000.0)+11644473600l)*10000000);
            long roundedTicks =ticks-(ticks % 3000000000L);
            String str = roundedTicks+"6A5AA1D4EAFF4E9FB37E23D68491D6F4";
            MessageDigest sha256 = MessageDigest.getInstance("SHA-256");
            byte[] hash = sha256.digest(String.valueOf(roundedTicks).concat("6A5AA1D4EAFF4E9FB37E23D68491D6F4").getBytes(StandardCharsets.UTF_8));
            StringBuilder hexString = new StringBuilder();
            for (byte b : hash) {
                String hex = Integer.toHexString(0xff & b);
                if (hex.length() == 1) {
                    hexString.append('0');
                }
                hexString.append(hex);
            }
            String SEC_MS_GEC = hexString.toString().toUpperCase();
            URL = String.format(
                    "wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&Sec-MS-GEC=%s&Sec-MS-GEC-Version=%s",
                    SEC_MS_GEC, SEC_MS_GEC_Version);
            System.out.println("Adjusted SEC_MS_GEC to : " + SEC_MS_GEC);
            //System.out.println("Adjusted SEC_MS_GEC_Version to : " + SEC_MS_GEC_Version);
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
}

**Comment by DavidLiu0536** [comment]
> Constan

这是修改的constants.java吧，原谅我大学学的java

**Comment by PoliceZ** [comment]
> > Constan
> 
> 这是修改的constants.java吧，原谅我大学学的java

完整类都放出来了，这个修改不应该有问题了哈

**Comment by PoliceZ** [comment]
> > Constan
> 
> 这是修改的constants.java吧，原谅我大学学的java

才看明白，你大学学java,那你不知道不同包可以有同名的类，还是完整的类放在那里你不知道搜索下package,或许你说不会回退代码，但直接说自己科班，这操作就看不懂了，人家开源的代码就用的这个名字，你认为不妥就去给写代码的提不规范的issu哈

**Comment by DavidLiu0536** [comment]
> > > Constan
> > 
> > 
> > 这是修改的constants.java吧，原谅我大学学的java
> 
> 才看明白，你大学学java,那你不知道不同包可以有同名的类，还是完整的类放在那里你不知道搜索下package,或许你说不会回退代码，但直接说自己科班，这操作就看不懂了，人家开源的代码就用的这个名字，你认为不妥就去给写代码的提不规范的issu哈

因为已经10年了。。早还给老师了 哈哈哈，白学了java，毕业后就没干过程序员，唉

**Comment by PoliceZ** [comment]
> > > > Constan
> > > 
> > > 
> > > 这是修改的constants.java吧，原谅我大学学的java
> > 
> > 才看明白，你大学学java,那你不知道不同包可以有同名的类，还是完整的类放在那里你不知道搜索下package,或许你说不会回退代码，但直接说自己科班，这操作就看不懂了，人家开源的代码就用的这个名字，你认为不妥就去给写代码的提不规范的issu哈
> 
> 因为已经10年了。。早还给老师了 哈哈哈，白学了java，毕业后就没干过程序员，唉

哦哦，有问题，找作者，没猜错你用的可能都是打好包的jar启动的，改不了也正常

**Comment by Mai-Onsyn** [comment]
test-v0.6.1提供开放的api配置 只要在设置里提供一个返回包含Sec-MS-GEC和Sec-MS-GEC-Version这两个key的json的api即可
