### ISSUE TITLE
谢谢大佬的辛勤劳苦，谢谢分享。新版本部署起来太繁杂了，可否打包一键部署？

### ISSUE THREAD

**Issue by narcissuslemon** [Mai-Onsyn/VeloVoice#8]
谢谢大佬的辛勤劳苦，谢谢分享。新版本部署起来太繁杂了，可否打包一键部署？

**Comment by Mai-Onsyn** [comment]
应该是不行 因为目前我看到的获取SecMSGEC的方法只有代理edge的https活动 必须用到mimproxy 而且我又不会python 只好用Java写 所以就挺麻烦的 但也不一定要用我的这个服务器 用其他大佬提供的可以获取到这两个必要值的api也是可以的
